name: Hello World Action

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python dependencies
      uses: actions/setup-python@v4
      with:
        cache: 'pip'
      run: pip install -r mistletoe requests

    - name: Install Node dependencies
      uses: actions/setup-node@v3
      run: npm install turndown
