name: Hello World Action

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: debian-latest

    steps:
    - name: Say Hello World
      run: node -e "console.log('Hello, World from node!');"
