name: Hello World Action

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python packages
      run: pip install -r requirements.txt

    - name: Install Node packages
      run: npm install turndown
